<?php

	$listwhat['Grass'] = array('grass', 'grasses', 'turf', 'greenery', 'sod', 'lawn', 'field', 'pasture', 'meadow', 'veld', 'mead', 'sward', 'lea', 'weed', 'bush', 'shrub', 'undergrowth', 'plant', 'hedge', 'sapling', 'lawns', 'fields', 'pastures', 'meadows', 'velds', 'meads', 'swards', 'leas', 'bushes', 'shrubs', 'undergrowth', 'plants', 'hedges', 'saplings', 'ghas', 'ghaas', 'ghans', 'ghass');
	$listwhat['Insects'] = array('insect', 'bug', 'ant', 'aphid', 'bee', 'beetle', 'butterfly', 'cockroach', 'dragonfly', 'flea', 'fruitfly', 'gnat', 'grasshopper', 'ladybug', 'mosquito', 'mite', 'moth', 'pest', 'spider', 'termite', 'tick', 'vermin', 'bedbug', 'arthropod', 'bumblebee', 'cootie', 'fly', 'hornet', 'louse', 'arachnid', 'ironman', 'stinkbug', 'wasp', 'cricket', 'locust', 'treehopper', 'keeda', 'keede', 'insects', 'bugs', 'ants', 'aphids', 'bees', 'beetles', 'butterflies', 'cockroaches', 'dragonflies', 'fruitflies', 'gnats', 'grasshoppers', 'ladybugs', 'mosquitoes', 'mites', 'moths', 'pests', 'spiders', 'termites', 'ticks', 'vermins', 'bedbugs', 'arthropods', 'bumblebees', 'cooties', 'flies', 'hornets', 'lice', 'arachnids', 'ironmen', 'stinkbugs', 'wasps', 'crickets', 'locusts', 'treehoppers' );
	$listwhat['StreetLight'] = array('streetlight', 'light', 'streetlamp', 'lamp', 'fluorescent light', 'flashlight', 'floodlight', 'lantern', 'beacon', 'flood lamp', 'flashlamp', 'illumination', 'luminescence', 'radiance', 'brightness', 'electric light', 'lamplight', 'incandescence', 'sidelight', 'wall light', 'batti', 'streetlights', 'lights', 'streetlamps', 'lamps', 'fluorescent lights', 'flashlights', 'floodlights', 'lanterns', 'beacons', 'flood lamps', 'flashlamps', 'electric lights', 'lamplights', 'sidelights', 'wall lights', 'battis');
	$listwhat['Tree'] = array('tree', 'woods', 'forest', 'overgrowth', 'ped', 'vriksha', 'trees', 'forests');
	$listwhat['Waste'] = array('waste', 'garbage', 'kachra', 'rubbish', 'refuse', 'litter', 'debris', 'dross', 'junk', 'detritus', 'dregs', 'leavings', 'remains', 'scrap', 'offscouring', 'sewage', 'effluent', 'effluvium', 'trash', 'discarded matter', 'filth', 'swill', 'muck', 'dross', 'scouring', 'leftover', 'remains', 'slops', 'mullock', 'grot', 'gash', 'debitage', 'draft', 'raffle', 'raff', 'cultch', 'stuff', 'clutter', 'rummage', 'crap', 'shit', 'kooda', 'bakwaas', 'heap', 'kachda', 'kuda');
	$listwhat['Smoke'] = array('smoke', 'vapor', 'smoulder', 'emit', 'smoking', 'emitting', 'smouldering', 'sniffing', 'cigarette', 'sutta', 'beedi', 'cigar', 'phook', 'phoonk', 'puff', 'puffing', 'inhale', 'inhaling');
	$listwhat['Sound'] = array('sound', 'loud', 'noise', 'din', 'hubbub', 'clamour', 'racket', 'uproar', 'tumult', 'commotion', 'pandemonium', 'clangour', 'crash', 'clatter', 'clash', 'babble', 'shouting', 'yelling', 'babel', 'bangarang', 'noisy', 'blaring', 'booming', 'deafening', 'roaring', 'thunderous', 'thundering', 'tumultous', 'clamorous', 'blasting', 'head-splitting', 'ear-splitting', 'ear-piercing', 'piercing', 'cacophonous', 'harsh', 'roudy');
	$listwhat['Internet'] = array('internet', 'net', 'lan', 'wifi', 'world wide web', 'www', 'network', 'information superhighway', 'arpanet', 'facebook', 'google', 'torrent', 'website', 'porn' );

	$listwhere['iiitBH4'] = array('bh4', 'boys hostel 4', 'boy hostel 4', 'boys residence 4', 'bh iv', 'boys hostel iv', 'boy hostel iv', 'boys residence iv' );
	$listwhere['iiitCC3'] = array('cc3', 'computer center 3', 'cv raman bhawan', 'cv raman bhavan', 'cc iii', 'computer center iii', 'cc 3', 'cciii', 'comp center 3', 'computer centre 3', 'computer centre iii', 'comp centre 3', 'comp centre iii');
	$listwhere['iiitVH1'] = array('vh1', 'visitor hostel 1', 'guest hostel 1', 'guest house 1', 'visitor house 1', 'vhi', 'visitor hostel i', 'guest hostel i', 'guest house i', 'visitor house i', 'vh 1', 'visitor hostel1', 'guest hostel1', 'guest house1', 'visitor house1', 'vhi', 'visitor hosteli', 'guest hosteli', 'guest housei', 'visitor housei');
	$listwhere['iiitCafeteria'] = array('cafeteria', 'cafe', 'cafet', 'bikaner', 'new canteen', 'canteen', 'bikanerwala', 'restaurant', 'aa sansthan');
	$listwhere['iiitDormitory'] = array('dormitory', 'dorm', 'recreation centre', 'festivity centre', 'function hall', 'hall', 'community centre', 'dorm quarter');
	$listwhere['iiitAdmin'] = array('admin', 'administration', 'central building', 'main building', 'director office', 'dean office', 'registrar office', 'examcell', 'accounts section', 'accounts office');
	$listwhere['iiitPavilion'] = array('pavilion', 'ground', 'stadium', 'football ground', 'cricket ground', 'hockey ground', 'athletic track', 'amphitheatre', 'playground', 'park', 'playing field', 'athletic stadium', 'sports field', 'asmita venue', 'effervescence venue');
?>
